import type { Metadata } from "next";
import "./styles.css";
import "../components/home/Hero.css";
import "../components/home/FeaturedProjects.css";
import "../components/home/SkillsOverview.css";
import "../components/layout/Footer.css";
import "../components/layout/Navbar.css";
import "./projects/ProjectsPage.css";
import "./about/AboutPage.css";

import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="container">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
